name: Build and Push to ECR

on:
  push:
    branches:
     - main
    paths:
      - 'app/**'
      - 'dockerfile'
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: "us-east-1"
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Compute IMAGE_TAG from GITHUB_SHA
      id: compute-tag
      run: echo "short_sha=${GITHUB_SHA:0:4}" >> $GITHUB_OUTPUT

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        role-session-name: plotly-gh-actions
        role-duration-seconds: 900 
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        mask-password: true

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: "plotly"
        IMAGE_TAG: ${{ steps.compute-tag.outputs.short_sha }}
      run: |
        ls
        docker build -f ./dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        DOCKER_BUILDKIT=0 docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Get tag Output
      run: echo ${{ steps.compute-tag.outputs.short_sha }}