name: Deploy to ECS with Terraform

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Docker Image Version'     
        required: false
        default: ''

permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
    AWS_REGION: "us-east-1"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        role-session-name: plotly-gh-actions
        role-duration-seconds: 1200
        aws-region: ${{ env.AWS_REGION }}

    - name: Determine Docker Tag
      id: prep
      run: |
        DOCKER_TAG=${{ github.event.inputs.version }}
        if [ -z "$DOCKER_TAG" ]; then
          DOCKER_TAG=${GITHUB_SHA::4}
        fi
        echo ::set-output name=tag::${DOCKER_TAG}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.3.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -var="IMAGE_TAG=${{ steps.prep.outputs.tag }}"

    - name: Terraform Apply
      run: terraform apply -var="IMAGE_TAG=${{ steps.prep.outputs.tag }}" -auto-approve


